
CC = g++
CFLAGS = -Wall
VFLAGS = -Wall -g

all:
	$(CC) $(CFLAGS) main.cpp -o utrp
debug:
	$(CC) $(VFLAGS) main.cpp -o utrp
folders:
	mkdir salidas/
	mkdir reportes/
	mkdir entradas/
clean:
	rm iterator
	rm utrp
